If DocType = ".par" Then
    Dim tmpSEDoc As SolidEdgePart.PartDocument = CType(SEDoc, SolidEdgePart.PartDocument)
    Dim DirName As String = IO.Path.GetDirectoryName(tmpSEDoc.FullName)
    
    Dim PropertySets As SolidEdgeFramework.PropertySets = CType(tmpSEDoc.Properties, SolidEdgeFramework.PropertySets)
    Dim PropertySet As SolidEdgeFramework.Properties = PropertySets.Item("Custom")
    Dim Prop As SolidEdgeFramework.Property = PropertySet.Item("index_number")

    Dim start_index As Integer = CInt(Prop.Value)

    For idx As Integer = start_index + 1 To 10
        Prop.Value = CStr(idx)
        PropertySet.Save()
        SEApp.DoIdle()

        SEApp.StartCommand(CType(11292, SolidEdgeFramework.SolidEdgeCommandConstants)) ' Update active level
        SEApp.DoIdle()

        tmpSEDoc.SaveCopyAs(String.Format("{0}\Part_{1}.par", DirName, CStr(idx)))
        SEApp.DoIdle()
    Next
End If
