' Contributed by @farfilli

Dim HoleDataCollection As SolidEdgePart.HoleDataCollection = Nothing

Select Case DocType
    Case ".par"
        Dim tmpSEDoc As SolidEdgePart.PartDocument = CType(SEDoc, SolidEdgePart.PartDocument)
        HoleDataCollection = tmpSEDoc.HoleDataCollection
    Case ".psm"
        Dim tmpSEDoc As SolidEdgePart.SheetMetalDocument = CType(SEDoc, SolidEdgePart.SheetMetalDocument)
        HoleDataCollection = tmpSEDoc.HoleDataCollection
End Select

If HoleDataCollection IsNot Nothing Then
    For Each item As SolidEdgePart.HoleData In HoleDataCollection

        If item.ThreadDescription = "R 2-11" Then

            item.Size = "R 2-11"
            item.Standard = "ISO Metric"
            item.SubType = "Filettatura gas conico"
            item.ThreadDiameterOption = CType(2, SolidEdgePart.ThreadDiameterOptionConstants)
            item.ThreadDepth = 0.02
            item.ThreadExternalDiameter = 0.0603
            item.ThreadTaperAngle = 0.031415926535897934

        End If

    Next
End If
