If DocType = ".dft" Then

    Dim tmpSEDoc As SolidEdgeDraft.DraftDocument = CType(SEDoc, SolidEdgeDraft.DraftDocument)

    Dim PartsLists As New List(Of SolidEdgeDraft.PartsList)
    Dim BackgroundNames As New List(Of String)

    Try
        If ExitStatus = 0 Then
            For Each Sheet As SolidEdgeDraft.Sheet In tmpSEDoc.Sheets
                If Sheet.Section.Type = 0 Then
                    For Each Item As Object In Sheet.DrawingObjects
                        Dim PartsList As SolidEdgeDraft.PartsList = TryCast(Item, SolidEdgeDraft.PartsList)
                        If PartsList IsNot Nothing Then
                            PartsLists.Add(PartsList)
                            BackgroundNames.Add(Sheet.Background.Name)
                        End If
                    Next
                End If
            Next
        End If
    Catch
        ExitStatus = 1
        ErrorMessageList.Add("Could not process sheets")
    End Try

    If ExitStatus = 0 And PartsLists.Count > 0 And PartsLists.Count = BackgroundNames.Count Then
        For i As Integer = 0 To PartsLists.Count - 1
            Try
                PartsLists(i).SavedSettings = BackgroundNames(i) + " NEW"
                PartsLists(i).Update()
                SEApp.DoIdle()
            Catch ex As Exception
                ExitStatus = 1
                'ErrorMessageList.Add($"Could not update parts list to '{BackgroundNames(i)} NEW'")
                Dim s As String
                s = String.Format("Could not update parts list to '{0} NEW'", BackgroundNames(i))
                ErrorMessageList.Add(s)
            End Try
        Next
    End If

    If ExitStatus = 0 Then
        Try
            SEDoc.Save()
            SEApp.DoIdle()
        Catch
            ExitStatus = 1
            ErrorMessageList.Add("Could not save file")
        End Try
    End If
End If